### PR TITLE
Added method to retrieve user id

### PR DESCRIPTION
**Pull request by MarsWilliams**
I added a method to retrieve a member's user id, so that this information can be used later for api queries. The method uses regular expressions to parse the id from the Selenium web element. @thekindlyone

### CODE REVIEW

**Comment by thekindlyone** [comment]
nice. I'll get back to this once I get a bit of time from paid projects. Meanwhile, if you are so inclined, look into ways of detecting spammers from their facebook frontpages. That was one of the goals when I started writing this.

**Comment by marsjoy** [comment]
I'll look in to that feature. I work with some spam detection algorithms in another context, so I'll see if I can alter them to apply to this context.

**Comment by thekindlyone** [comment]
We run a nice little group [here](https://www.facebook.com/groups/python.programmers/)
The code was written to help in administrating this group and auto accepting and banning the obvious cases.
You are invited to join :)

**Comment by marsjoy** [comment]
Thanks! I have joined it. Also, I forgot to mention, but the 'See More'
button changes it's text variably, so I am working on some logic to make
sure that the driver is able to click on the link no matter what name the
facebook script throws out. :)

**Pull request merged**
